name: Pre-Merge Checks

on: [pull_request, push]

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Start Server
        run: npm start
      - name: Unit Tests
        uses: cypress-io/github-action@v6
        with:
          component: true
      - name: E2E Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
      - name: ESLint
        run: npm run lint
      - name: Prettier
        run: npm run format